uCredit-Dev/ucredit_frontend_typescript

public/index.html, src/components/dashboard/Content.tsx, src/components/dashboard/InfoMenu.tsx, src/components/dashboard/course-list/CourseComponent.tsx, src/components/dashboard/course-list/CourseList.tsx, src/components/dashboard/course-search/Search.tsx, src/components/dashboard/course-search/query-components/CourseCard.tsx, src/components/dashboard/course-search/query-components/Filters.tsx, src/components/dashboard/course-search/query-components/Form.tsx, src/components/dashboard/course-search/query-components/SearchList.tsx, src/components/dashboard/course-search/search-results/CourseDisplay.tsx, src/components/dashboard/course-search/search-results/CourseVersion.tsx, src/components/dashboard/course-search/search-results/Placeholder.tsx, src/components/dashboard/course-search/search-results/SisCourse.tsx, src/components/dashboard/right-column-info/CourseBar.tsx, src/components/dashboard/right-column-info/Distributions.tsx, src/components/dashboard/right-column-info/FineDistribution.tsx, src/components/dashboard/right-column-info/InfoCards.tsx, src/components/dashboard/right-column-info/distributionFunctions.tsx, src/resources/assets.tsx, src/resources/commonTypes.tsx, src/resources/majors.tsx, src/slices/searchSlice.ts
Search:
- Search filters now support multi-select
- Added searching by level (Lower vs. Upper level)
- Entire form area scrolls, rather than just the search results.
- Level and writing intensive information added to course display
- Small detail changes to make placeholder adding more explicit.
Plan Overview:
- Widened plan overview for better user experience
- Reworded title to be "Degree Progress"
- Minor restyling to fine requirements
- Modularization of fine requirements
=> Search and Plan overview updates.

src/components/dashboard/right-column-info/CourseBar.tsx, src/components/dashboard/right-column-info/DistributionPopup.tsx, src/components/dashboard/right-column-info/Distributions.tsx, src/components/dashboard/right-column-info/FineDistribution.tsx, src/components/dashboard/right-column-info/distributionFunctions.tsx
- Added plus buttons next to the distributions
- Clicking on a plus brings up a popup with the corresponding distribution and all of the user courses
- Clicking on the plus will add the course to the distribution
- Clicking on the minus will subtract the course from the distribution
- The save button will enact the changes, cancel will not
- Example of adding Economics of Health to the Computer Science and Upper Level CS distributions.
=> Added Ability to Add Courses to Distributions Manually

package.json, public/index.html, src/components/App.tsx, src/components/dashboard/Content.tsx, src/components/dashboard/course-list/CourseList.tsx, src/components/dashboard/course-list/Semester.tsx, src/components/dashboard/right-column-info/CourseBar.tsx, src/components/dashboard/right-column-info/FineDistribution.tsx, src/components/dashboard/right-column-info/PlanChoose.tsx, src/components/dashboard/right-column-info/ShareLinksPopup.tsx, src/components/dashboard/right-column-info/distributionFunctions.tsx, src/components/login/DashboardEntry.tsx, src/components/login/UserSection.tsx, src/components/popups/AddingPrereqPopup.tsx, src/components/popups/CourseDisplayPopup.tsx, src/components/popups/course-search/prereqs/PrereqDisplay.tsx, src/components/popups/course-search/query-components/Filters.tsx, src/components/popups/course-search/query-components/Form.tsx, src/components/popups/course-search/search-results/CourseDisplay.tsx, src/components/popups/course-search/search-results/Placeholder.tsx, src/components/popups/course-search/search-results/SisCourse.tsx, src/resources/GenerateNewPlan.tsx, src/resources/assets.tsx, src/resources/majors.tsx, src/slices/currentPlanSlice.ts, src/slices/popupSlice.ts, tsconfig.json
Prereq-adding flow
- Prereqs can now be added when one opens course display in the plan dashboard.
Fine req styling
- Fine requirements are now converted to JSX using react-html-parser.
Bug fixes
- Login didn't work for specific browsers due to cookie-setting issue. This has been fixed.
- Fine requirements for old and new cs degrees should work now.
=> Bug fixes, prereq adding flow feature, styling for fine reqs

src/components/dashboard/course-list/CourseList.tsx
Reverts MattLiu-mygit/ucredit_frontend_typescript#200
=> Revert "added Front AddButton to dashboard"

src/resources/commonTypes.tsx, src/resources/majors.tsx
Implemented schemas for old BS CS, new BA CS, and new minor CS
=> feat: adding CS schemas

src/components/App.tsx, src/components/dashboard/HandleUserEntryDummy.tsx, src/components/dashboard/course-list/CourseComponent.tsx, src/components/dashboard/right-column-info/ActionBar.tsx, src/components/dashboard/right-column-info/CourseBar.tsx, src/components/dashboard/right-column-info/DistributionBars.tsx, src/components/dashboard/right-column-info/distributionFunctions.tsx, src/components/popups/course-search/query-components/Form.tsx, src/components/popups/course-search/search-results/CourseVersion.tsx, src/resources/commonTypes.tsx, src/resources/majors.tsx
Refactoring code:
- Shifted from handling promises in HandleUserEntryDummy.tsx from using the Pyramid of Doom Promise Handling technique to async await functions.
- Added helper functions based on SonarLint logic complexity suggestions in multiple files throughout the code.
- Note: future tasks will include making sure this linter is satisfied before pushing. Additionally, new tasks in the future will include refactoring current code so that it is satisfied with the linter.
Majors:
- Manually merged Mark's work with adding CS Majors and minors as he accidentally made a pull request to main.
- Majors and minors added
- BS in CS old version
- BA in CS
- CS Minor
=> fix: began refactoring code and merged Mark's work with majors

.github/workflows/codeql-analysis.yml
Some interesting security data that we can view as we develop the project.
=> Added security analysis workflow to project.

.github/workflows/eslint.yml
Not sure whether to merge to dev or master; not sure if this works, but it's harmless to commit it in anyways.
=> Add eslint workflow

src/components/dashboard/HandleUserEntryDummy.tsx, src/components/dashboard/InfoMenu.tsx, src/components/dashboard/dashboard.test.tsx, src/components/dashboard/degree-info/ActionBar.tsx, src/components/dashboard/degree-info/Distributions.tsx, src/components/dashboard/degree-info/PlanChoose.tsx, src/components/popups/PlanAdd.tsx, src/resources/GenerateNewPlan.tsx, src/resources/commonTypes.tsx, src/resources/majors.tsx, src/slices/popupSlice.ts
Create multi-select dropdowns to allow users to add/delete multiple majors in `PlanAdd` and `ActionBar`
=> feat: enable plans to have multiple majors

src/components/dashboard/dashboard.test.tsx
Fix issues with mock react-select
=> fix/mock react-select

lib/components/dashboard/index.tsx, pages/login/[[...token]].tsx, pages/reviewer/[...id].tsx
Fix experiments infinite loop
Login only has a single mock user, but you can log in with any id now
=> Iter 02 backdoor login: set up with local database

lib/components/dashboard/menus/HamburgerMenu.tsx, lib/components/dashboard/menus/PlanEditMenu.tsx
=> Reviewer dashboard debug

lib/components/landing-page/Introduce.tsx, lib/components/landing-page/assets/data/promoData.ts, pages/about.tsx, pages/index.tsx
This solution will check if the app is in mobile every re render. This means that it will not work if you simply switch from desktop to mobile in the inspect element, you must switch it first and then reload to cause the re-render. This won't be an issue for mobile devices, because they will already be on mobile, and the initial render will indicate to the state that it's a mobile device.
=> Fix SVG rendering issues in About Page

lib/resources/majors.tsx
Implementation: BS CS major for old and new requirements
=> Added new and old CS majors

lib/components/reviewer/Reviewee.tsx
On going to reviewer dashboard, only first reviewer has plans open (UI issue); make all other reviewer's plan lists open. 
Set state of showPlans to be true. 
Tested locally. Asked others to add jdeng25 as a reviewer so that user jdeng25 would be reviewing multiple plans. Confirmed that the reviewer dashboard UI displays all reviewees' plans as expanded.
=> DEV-54 On going to reviewer dashboard, make all other reviewee's plan lists open

lib/components/popups/course-search/query-components/Filters.tsx, pages/dashboard.tsx, pages/login/[[...token]].tsx, pages/reviewer/[...id].tsx
yearRange is stored in localStorage indefinitely with no set expiration. Therefore, users may not see that there are more version years if their yearRange is outdated. (creds to matt!)
switch to sessionStorage where the data's lifespan is while the tab is open
=> DEV-65: cache yearRange in sessionStorage

e2e/e2eFixtures.ts, lib/components/dashboard/menus/HamburgerMenu.tsx, lib/resources/assets.tsx
The new backend deployment links are ready to have a trial period in development.
ucredit-dev: [https://ucredit-dev.onrender.com](https://ucredit-dev.onrender.com) is a deployment of the [DEV-43](https://github.com/uCredit-Dev/uCredit-API/tree/DEV-43) branch 
ucredit-api: [https://ucredit-api.onrender.com](https://ucredit-api.onrender.com) is a deployment of the [main](https://github.com/uCredit-Dev/uCredit-API/tree/main) branch 
Mr. Soylu whitelisted the production link with JHU SSO. 
todos: 
- merge this PR and [DEV-43: changes to deploy api on onrender](https://github.com/uCredit-Dev/uCredit-API/pull/59) into corresponding development branches 
- test for a week on https://ucredit-frontend-typescript-local.vercel.app/login
- merge dev into backend main and development into frontend …
=> DEV-43 Connect new backend deployment into development 

lib/components/MobileTurnPage.tsx, lib/components/dashboard/dashboard.test.tsx, lib/components/dashboard/degree-info/AddReviewer.tsx, lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/components/dashboard/degree-info/FineDistribution.tsx, lib/components/popups/DeleteCoursePopup.tsx, lib/components/popups/DeletePlanPopup.tsx, lib/components/popups/DeleteYearPopup.tsx, lib/components/popups/ExperimentDevBoardPopup.tsx, lib/components/popups/ExperimentNumber.tsx, lib/components/popups/ExperimentPopup.tsx, lib/components/popups/FeedbackNotification.tsx, lib/components/popups/PlanAdd.tsx, lib/components/popups/course-search/cart/CartCourseList.tsx, lib/components/popups/course-search/cart/CartCourseListItem.tsx, lib/components/popups/course-search/cart/FineRequirementItem.tsx, lib/components/popups/course-search/cart/FineRequirementsList.tsx, lib/components/popups/course-search/prereqs/PrereqDropdown.tsx, lib/components/popups/course-search/query-components/CourseCard.tsx, lib/components/popups/course-search/query-components/Filters.tsx, lib/components/popups/course-search/query-components/Form.tsx, lib/components/popups/course-search/search-results/CourseEvalCard.tsx, lib/components/popups/course-search/search-results/CourseEvalSection.tsx, lib/components/popups/course-search/search-results/CourseVersion.tsx, lib/components/reviewer/Search.tsx, lib/resources/OutsideAlerter.tsx
=> DEV-67: fix react import errors 

lib/components/landing-page/Promo.tsx
=> DEV-96: disable JHU login button and add popup on hover

pages/login/[[...token]].tsx
This reverts commit 4df1e45ca7bfe2bc9cac619ac258b3366d41e4e8, reversing changes made to 1a2cd78c4894c762730d50217c845a3620529585.
JHU login enable
=> Revert "Merge pull request #416 from uCredit-Dev/DEV-96"

lib/components/dashboard/degree-info/distributionFunctions.tsx, lib/components/dashboard/index.tsx, lib/components/popups/course-search/Cart.tsx, lib/components/popups/course-search/Search.tsx, lib/components/popups/course-search/cart/CartCourseList.tsx, lib/components/popups/course-search/query-components/Form.tsx, lib/components/popups/course-search/query-components/SearchList.tsx, lib/resources/assets.tsx, lib/resources/majors.tsx
Backend PR: https://github.com/uCredit-Dev/uCredit-API/pull/77
Some PRs were merged into dev such as #413 #430 in frontend and https://github.com/uCredit-Dev/uCredit-API/pull/70 https://github.com/uCredit-Dev/uCredit-API/pull/72 and https://github.com/uCredit-Dev/uCredit-API/pull/64 in backend. However, we are noticing some bugs in development branch which we need to address before merging these changes into master. (need to do this asap because development branch is lagging behind a lot! aka the JWT changes still didn't make it to production). 
DEV-120 task was originally to do with improving the speed of the new search route, more on that in https://github.com/uCredit-Dev/uCredit-API/pull/77. 
- Degree progress calculation crashes client 
- handle course.areas undefined case
- Migrated …
=> DEV-120: fix bugs in search 

pages/_app.tsx, pages/index.tsx
Why does ucredit.me not show up when we search up ucredit? 
- Our robots.txt file is available and correct (all scrawlers allowed on all paths) 
- To [test our robots.txt further](https://search.google.com/search-console/welcome?action=inspect&utm_medium=referral&utm_campaign=9012289), we need to add a [verification meta tag](https://support.google.com/webmasters/answer/9008080?visit_id=638153694359967090-2913419715&rd=1)  
- Our domain is indexed by google (try searching `site:ucredit.me`)
- How to optimize search rank 
- Add a [sitemap](https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps) seems like an overkill 
- Add [meta tags](https://ahrefs.com/blog/seo-meta-tags/)
- To the home page! I think we had the title tag in the wrong file 
- Request Google to …
=> IN-49: add meta tags to landing page for SEO

lib/components/dashboard/HandlePlanShareDummy.tsx
Previously, importing a plan could become stuck if there were illegal courses (such as duplicated courses in the same semester and year) in the plan.
I added proper rejection of the promise in the `addCourse` function and error handling to the `addImportedCourses` function to ensure that illegal courses are bypassed. I also changed the logic of checking termination to ensure proper termination when courses are bypassed.
I tested locally and ensured everything works as expected.
=> DEV-192: Debug import plan crashing

lib/components/landing-page/assets/data/teamList.ts
=> DEV-170 fix nish's picture on team page

lib/components/popups/course-search/cart/FineRequirementItem.tsx, lib/components/popups/course-search/cart/FineRequirementsList.tsx
Solved a TODO in codebase by adding documentation for fine requirement components
=> DEV-178: Add documentation for fine requirement components

lib/resources/majors.tsx
Description: Writing Public Health major, , delineate foundational quantitative, social science, natural science requirements with generic degree requirements, update writing intensive to match new reintroduction to writing requirement, make descriptions up to date.
Replicated the formatting of other majors though public health is slightly weird.
Testing: Tested locally, works good.
=> DEV-194 Write new major: Public Health

lib/components/popups/course-search/postreqs/PostReqSection.tsx
=> remove extra question mark

lib/components/dashboard/Actionbar.tsx, lib/resources/majors.tsx
=> Update dev with master

lib/resources/majors.tsx
really hard change.
Please test extremely carefully before approving.
=> fixed doubleCS minor change

.github/workflows/eslint.yml, lib/components/popups/course-search/prereqs/PrereqDisplay.tsx, lib/components/popups/course-search/prereqs/PrereqDropdown.tsx, lib/index.css, lib/resources/assets.tsx, lib/resources/redux_sample/Counter.module.css
1. bug: currently can't click on satisfied prerequisites 
2. bug2: prereqs shown are inaccurate for inspected course; lagging  
3. bug3: plan says prereq not satisfied but course popup says otherwise   
- for bug 2, the plan was looking at the newest version of course and the popup was looking at the correct version of the course 
- for bug 3, look at courseToShow (UserCourse) which will have accurate prereq 
- for bug 1, fix minor coding error
=> Fix bug where you can't click satisfied prerequisites
