uCredit-Dev/ucredit_frontend_typescript

src/components/dashboard/course-list/CourseComponent.tsx, src/components/dashboard/course-list/CourseDraggable.tsx, src/components/dashboard/course-list/CourseList.tsx, src/components/dashboard/course-list/Semester.tsx, src/components/dashboard/course-list/YearComponent.tsx, src/components/dashboard/course-list/YearDraggable.tsx, src/components/popups/course-search/prereqs/PrereqDisplay.tsx, src/components/popups/course-search/query-components/Filters.tsx, src/components/popups/course-search/query-components/Form.tsx, src/resources/assets.tsx, src/resources/svg/Grab.svg
Draggable symbols
- Implemented to make dragging more intuitive
Filter now auto-opens on opening search popout
Bug squashes
- Prereqs weren't being displayed correctly when opening courses from plan dashboard.
- Years were being randomized when switching plans.
=> feat, bug-fix: Added draggable symbols to course and year components, made filter auto open, bug squashing

lib/resources/majors.tsx
CS minor old & new
- split single bar into multiple distributions 
- allowed users to fulfill focus areas 
BS AMS
- fixed typos & issues with electives
=> Correct CS minor && BS AMS 

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/components/dashboard/degree-info/distributionFunctions.tsx, lib/resources/commonTypes.tsx, lib/resources/majors.tsx
- exclusive is a string[] 
- each string is a whitelisted distribution that can overlap with given distribution 
- also applies to fine requirements 
Until now, exclusive has been a boolean field of distribution and fine requirement objects.
- `exclusive` is true: exclusive to ALL, cannot double count with any 
- `exclusive` is false: exclusive to NONE, can double count with any 
But `exclusive` as a boolean cannot provide logic for 'gray zones' where a distribution is exclusive to some but not all distributions. Take any KSAS degree, for example. The `Humanities` distribution can overlap with the `Writing Intensive` distribution but _cannot_ overlap with the `Social Sciences`. Exclusive can be neither `true` nor `false`. 
- Edited type definitions for `requirement` of …
=> feat: implemented exclusive as whitelist 

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/components/dashboard/degree-info/distributionFunctions.tsx, lib/resources/commonTypes.tsx, lib/resources/majors.tsx
- removed double_count as a boolean field 
- renamed exclusive as double_count
The field name `exclusive` is misleading, as it is a whitelist of distribution names that CAN overlap. To avoid confusion and improve readability, what used to be `exclusive` is now called `double_count`. What used to be `double_count` is removed, as it served no purpose. 
- modify distribution and fine requirement schemas 
- reflect change in requirement checking functions 
- replace exclusive and remove double_count in `majors.tsx`
- undefined or []: the distribution can overlap with any others
- misleading, but saves us LOTS of typing
- ['N/A']: it may not overlap with any other distributions
- ['A', 'B']: it may overlap with distributions with the name field === 'A' or 'B'
- in fine requirements, we use the …
=> Rename exclusive to double_count

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/resources/majors.tsx
The default value (or the absence) of `double_count` signified that the distribution could overlap freely with any other. We did this because it saved us typing. To avoid confusion, however, we are changing the logic so that the absence of `double_count` indicates no double count.
- modified double_count field checking for distributions and fine requirements 
- removed all instances of `double_count: ['N/A']` in majors.tsx
- add `double_count: ['All']` in majors.tsx where necessary 
- undefined or []: cannot double count with any (aka is exclusive) 
- ['A', 'B']: can double count with A or B 
- ['All']: can overlap with all distributions 
- saves us from typing all the distributions 
Tested locally. Other open PRs will need to pull these changes and ensure their code is compatible with …
=> fix: double_count default is no double count 

lib/resources/majors.tsx
I created three distributions:
1. Calculus Courses (You have to take Calculus I, II, and III with some alternative options...)
2. 200-Level or 300-Level (self-explanatory, 1 course for this)
3. 300-Level or Above (3 math courses; used updated pathing for this to satisfy an alternate route: 1 AMS course and 2 math courses)
=> Added Math Minor

lib/components/popups/course-search/Cart.tsx
The issue with the cart was that (), AND, OR, NOT operators were being ignored, so we were searching for each phrase in the condition and aggregating all of the resulting courses. For example, for CS upper level courses, we don't want to include Intro Algos in the results, but because NOT was ignored, Intro Algos was being included in the results.
Since the required set of courses is a subset of the courses returned by the cart while ignoring the AND, OR and NOT operators in the criteria string, we can test to see if each of the courses in the super set satisfy the criteria of the requirement. 
Thus, we iterated through each of the courses in the superset, converted them to an instance of the Course datatype/object and then tested them with the CheckRequirementsSatisfied() function.
We …
=> cart parses successfully

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/components/dashboard/degree-info/distributionFunctions.tsx, lib/resources/commonTypes.tsx, lib/resources/majors.tsx, package.json
###Adding upper level CS labs like Augmented Reality (EN.601.454) does not update the degree progress bars. 
Remove `exclusive: true` line in the Upper-Level Courses distribution of CS_Minor_Old. 
It had both `pathing: 1 `and `exclusive: true`. It's unclear why bug occurred. Perhaps the course satisfying a fine requirement (Applications) prevented this course from also satisfying the parent distribution (Upper-Level Courses). This should not be the case, but it might be. 
Tested with various upper level CS labs like Computer Graphics, OS, FP, OOSE, and Compilers.
=> DEV-35 Remove exclusive field to fix cS upper level labs bug

lib/components/popups/course-search/query-components/Form.tsx
no search results for spring semesters in future (e.g. Spring 2023 and onwards) 
Request to '/api/search' had param year: 2023 for which obviously we don't have matching courses yet. Code in Form.tsx assumes that SIS will have added spring courses by October but obviously, this has not been the case as of now. That is why this bug occurred on October 1st. The year param should only be included IF course data is available for that year. 
We may want to check if we have courses for Spring 202X before querying for it.
=> fix: fixed but with not being able to search future spring courses

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/resources/majors.tsx
Testing with [Matthew Liu's plan](https://ucredit.me/share?_id=61e644ff68480b0004c9e6e9) which should satisfy every distribution and fine requirement. 
1. Practical Ethics for Leaders does not satisfy Computer Science > Computer Ethics 
2. Lower Level Undergraduate not fulfilled despite all course requirements being met 
3. Computer Science Classifications distribution fine requirements not being fulfilled when there are 3 applicable courses: Artificial Intelligence, OOSE, and Functional Programming 
1. add Practical Ethics course number to distribution criteria string 
2. (and 3) double_count is restricting us from considering other distributions. Only update double_count if course satisfies AND updates credits for general distribution. ALWAYS consider a course for all fine requirements. …
=> DEV-36: fix bug with double_count in bsCS_new

lib/components/dashboard/Comments.tsx
After a user deletes a comment, if the page reloads (e.g. page is manually refreshed, user opens comments list, user replies to another comment), the deleted comment reappears. The issue was occuring because in the comments deleteHandler written over the summer, the Redux state was not being updated. 
The comments deleteHandler updates the Redux state using updateThreads. 
Tested locally. Created new comments and deleted them.
=> DEV-32 Comment deletion is broken

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/resources/majors.tsx
- CS Science credit requirements should be 10, not 8 
- Intro to anthropology should count towards Writing intensive requirements in BME 
- pathing=1 is satisfied but Focus Area distribution of BME is not satisfied  
For a better description, see [JIRA](https://ucredit-fall22.atlassian.net/jira/software/c/projects/DEV/boards/1?modal=detail&selectedIssue=DEV-50) board. 
- edit bscs_old and bscs_new in majors.tsx 
- change the order of distribution bars in BME 
- before, electives distribution was placed before writing intensive
- electives has no `double counting` distributions 
- hence the course was never considered for writing intensive 
- make electives only double count with writing intensive (other dists -> elective -> writing intensive) 
- when multiple paths are satisfied at once, …
=> DEV-47&50: fixed bugs within BME and CS

pages/dashboard.tsx, pages/login/[[...token]].tsx
If a user starts on their reviewee’s plan then tries to return to their own plan, the reviewee’s plan is displayed instead of their own plan. When a user inspects their reviewee’s plan, the URL contains characters after [ucredit.me/dashboard](http://ucredit.me/dashboard) (e.g. https://ucredit.me/dashboard?plan=61e4bfe7d834e2000448576d&mode=view). If the user refreshes while viewing the reviewee’s plan, the page reloads and redirects to /login then /dashboard. The page still displays the reviewee’s plan but the URL becomes [ucredit.me/dashboard](http://ucredit.me/dashboard), without the subsequent characters. If the user then tries to return to their own planning dashboard, the reviewee’s plan still displays.
Implementation is in pages/dashboard.tsx and pages/login/[[...token]].tsx. Used …
=> DEV-29 Reviewer reloads reviewee’s plan and returns to own plan, reviewee’s plan still displays

lib/components/popups/course-search/query-components/Form.tsx
added Spring 2023 courses into production db 
when trying to search for courses to add in spring 2023, searchFilter.year is still 2022 
in Form.tsx `handleFutureYear` function we determine the searchFilter.year depending on whether searchFilter.term is fall or spring. If term is spring and we are in October (when SIS courses are released), we want 2023 to be an option. 
see related PR in backend:[https://github.com/uCredit-Dev/uCredit-API/pull/53]( https://github.com/uCredit-Dev/uCredit-API/pull/53 )
UPDATE: noticed that when searching for courses in Summer 2023, version year is set as 2023 and returns no courses. It should be 2022 because summer courses are not yet released.
turns out getMonth() returns range [0,11] not [1,12]
=> DEV-59: fix bug with 2023 spring

pages/dashboard.tsx
Sometimes when a reviewer tries to access a reviewee's plan through the reviewer dashboard, the toast error "You do not have access to this plan!" appears. The cause of the issue was due to only checking reviewee's first reviewer instead of checking all reviewers.  
Added a for loop to increment through a reviewee's array of reviewers. 
Tested locally. Logged in as jdeng25 (reviewer), tried accessing kyang53, mpark63, and adeo1's plans (reviewees).
=> DEV-63 Reviewer tries to access reviewee's plan, toast error appears

lib/components/dashboard/Actionbar.tsx, lib/components/dashboard/HandlePlanShareDummy.tsx, lib/components/dashboard/HandleUserInfoSetupDummy.tsx, lib/components/dashboard/course-list/CourseList.tsx, lib/components/dashboard/course-list/Semester.tsx, lib/components/dashboard/course-list/YearSettingsDropdown.tsx, lib/components/dashboard/degree-info/ShareLinksPopup.tsx, lib/components/dashboard/menus/PlanEditMenu.tsx, lib/components/dashboard/menus/reviewers/CurrentReviewers.tsx, lib/components/dashboard/menus/reviewers/ReviewerSearchResults.tsx, lib/components/popups/ApplicationFormPopup.tsx, lib/components/popups/CourseDisplayPopup.tsx, lib/components/popups/DeleteCoursePopup.tsx, lib/components/popups/DeletePlanPopup.tsx, lib/components/popups/DeleteYearPopup.tsx, lib/components/popups/ExperimentDevBoardPopup.tsx, lib/components/popups/PlanAdd.tsx, lib/components/popups/course-search/search-results/CourseDisplay.tsx, lib/components/reviewer/PlanSummary.tsx, lib/components/reviewer/Reviewee.tsx, lib/resources/GenerateNewPlan.tsx, lib/resources/commonTypes.tsx, pages/dashboard.tsx, pages/login/[[...token]].tsx, pages/reviewer/[...id].tsx
Currently when a user holds the delete button on the “Update Degrees” field, there are multiple “You must have at least one major!” popups that fill the screen for a few seconds. It is preferable to have one popup at a time.
As such, I created a toast ID for every unique toast.success(), toast.error(), toast.warn(), and toast.info() call. The toast container automatically ensures that two toast notifications with the same ID are not active at the same time. This solves the initial problem of having more than one "You must have at least one major!" popup when the user holds the delete button in the "Update Degrees" field.
=> Prevent Notification Duplication (DEV-18)

pages/_app.tsx
We discovered that users may not realize their issue if they have multiple notifications, because users would have to scroll down to find the latest notification. Now, the order of notifications has been reversed, so the most recent notification appears first.
=> Make notification appear in reverse chronological order

lib/components/dashboard/HandlePlanShareDummy.tsx
inspecting course in imported plan crashes client-side 
add version field to the POST api/courses call request body 
todo: add version to course documents lacking it 
update: todo is done 
[https://github.com/uCredit-Dev/uCredit-API/pull/55](https://github.com/uCredit-Dev/uCredit-API/pull/55 )
=> DEV-66: courses is imported plan should have Version

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx, lib/components/popups/course-search/cart/CartCourseListItem.tsx, lib/components/popups/course-search/cart/FineRequirementsList.tsx, lib/components/roadmap/Banner.tsx
Warning: Each child in a list should have a unique "key" prop error 
add the key props in the render methods of Laptop and DistributionsJSX
warning disappears
=> DEV-90: add key props to render of Laptop and DistributionJSX

pages/login/[[...token]].tsx
Heroku API deployment will be offline starting tomorrow.
Render can handle all routes except for the **JHU login route**. So JHU login feature will be unavailable until IT whitelists our new API link. Sorry for the delay in getting it whitelisted with JHU SSO! Hopefully it should be done by Tuesday. 11/29 
- disable JHU login button 
- show maintenance popup on hover 
Note that if the user has a valid connect.sid cookie (hash value), the frontend will automatically attempt to log them in using sessions DB login. Otherwise, they will have to continue as guest. 
We will merge this PR at November 28th 1AM. 
We will revert this commit whenever render deployment gets whitelisted.
=> DEV-96: disable JHU login button and add popup on hover

lib/components/dashboard/menus/reviewers/ReviewerSearchResults.tsx
**Description**
Users cannot remove pending reviewers (reviewers who were requested but have not yet accepted the request).
**Implementation**
In the isReviewer function in ReviewerSearchResults.tsx, the function only returned the ID of a proposed reviewer if the status of that reviewer was not "pending." This implementation simply removed the check of the proposed reviewers' status, so now reviewers of all statuses (Approved, Rejected, Under Review, and Pending) can be removed.
**Testing**
Tested locally. Created a new account and added the actual account linked to my JHED as a reviewer. Then, I attempted to delete my reviewer and succeeded. To check that the process of adding reviewers wasn't affected by my code fix, I created a second dummy account and added myself as a review. I then …
=> DEV-22 - users can now remove pending reviewers

lib/components/dashboard/Comments.tsx, lib/components/dashboard/course-list/YearComponent.tsx, lib/components/dashboard/degree-info/DistributionBarsJSX.tsx
Toggling year menu when year is closed causes menu to immediately close when moving towards menu.
If a year is collapsed, when the user opens the year settings dropdown, clicking outside of the dropdown or clicking the three dots icon closes the dropdown. 
Tested locally.
I also refactored handleClickOutside in Comments.tsx.
=> DEV-53 Toggling year menu when year is closed causes menu to immediately close when moving towards menu

lib/components/dashboard/Actionbar.tsx, lib/components/dashboard/HandlePlanShareDummy.tsx, lib/components/dashboard/course-list/Semester.tsx, lib/components/dashboard/menus/PlanEditMenu.tsx, lib/components/popups/CourseDisplayPopup.tsx, lib/components/popups/course-search/search-results/CourseDisplay.tsx, lib/resources/GenerateNewPlan.tsx
too many outdated guestUser documents in db that slow our db queries  
The course, distribution, plan, and year documents **belonging to guestUser** should expire 24 hours after their creation. 
The expireAt field is now a [TTL index](https://www.mongodb.com/docs/manual/core/index-ttl/). 
therefore, whenever we set the value of expireAt in frontend, it should be `Date.now()` or undefined
=> DEV-89: make guestUser documents expire after a day

lib/components/dashboard/HandlePlanShareDummy.tsx, lib/components/dashboard/course-list/CourseList.tsx, lib/components/dashboard/course-list/Semester.tsx, lib/components/dashboard/index.tsx, lib/components/popups/course-search/Cart.tsx, lib/components/popups/course-search/Search.tsx, lib/components/popups/course-search/cart/CartCourseList.tsx, lib/components/popups/course-search/query-components/Form.tsx, lib/components/popups/course-search/query-components/SearchList.tsx, lib/resources/assets.tsx, lib/resources/commonTypes.tsx, lib/slices/searchSlice.ts, lib/slices/userSlice.ts, pages/index.tsx
Backend PR : https://github.com/uCredit-Dev/uCredit-API/pull/69 
- migrate `performSmartSearch` logic to backend
- integrate frontend with new /search route and pagination 
- remove unnecessary filtering of courses (backend does all filtering)
- cache courses once with `/api/coursesByPlan` route instead of multiple `/search` calls 
- !! work in progress !!
note: course searches for prereq checking and fine requirements still uses same search logic now `/cartSearch`. Better done as part of the distributions migration project... 
See under files changed tab 
Tested search locally by course title, number, with various applicable filters. Confirmed that prereq checking and fine requirements searching still works. 
todo: try importing plan / reviewing plan
=> DEV-44: search result pagination 

lib/components/dashboard/course-list/Semester.tsx, lib/components/dashboard/menus/PlanEditMenu.tsx, lib/components/popups/CourseDisplayPopup.tsx, lib/components/popups/course-search/search-results/CourseDisplay.tsx, lib/resources/assets.tsx, lib/resources/commonTypes.tsx
If a user tries to add a duplicate course in the same semester, a toast error will be displayed and the course is not added.
Works with DEV-125 branch on backend repo. 
Each time the add course route is called on front end, toast is displayed if error is returned and prints error message.
Also, when adding prereqs, the error causes adding prereq mode to close.
Local testing done
attempted to add the same course (i.e. adding Gateway Python twice) which triggers toast
attempted to add courses with same number but different names (i.e. two different ProfComm classes) which is allowed
=> DEV-125: display toast on error response for adding courses

lib/components/dashboard/degree-info/CourseBar.tsx, lib/components/dashboard/degree-info/InfoMenu.tsx, lib/components/popups/CourseDisplayPopup.tsx, lib/components/popups/course-search/search-results/Placeholder.tsx, lib/resources/assets.tsx, lib/slices/currentPlanSlice.ts, lib/slices/popupSlice.ts
**Description**
In the distributions branch on frontend, clicking on the total credits bar in the tracker caused the app to crash. So the solution is to make the total credits bar unclickable. 
**Implementation**
In the CourseBar.tsx, openCartPopup function is called when the CourseBar is clicked. I made the total credits bar unclickable by changing how the correct distribution was filtered from the distributions. 
**Testing**
Tested locally but only on a new plan with no courses added. I have two dev accounts, mkim224 and mkim25, but for some reason they don't have majors in the plans containing courses (and thus only the total credits bar showed up in the tracker). So I created a new plan which meant distribution bars were shown in the tracker, but I couldn't add new courses and check …
=> DIS-32 make total credits bar unclickable

lib/components/dashboard/Comments.tsx
**Description:**
If a user opens the menu or the reviewer icon(the "person" icon in the action bar), a click on the comment icon no longer opens the comment view.
**Implementation:**
The issue is that, if the comment view is open, clicking outside the comment view will close it.  However, the click used to open the comment view triggers the corresponding event listener after the comment view is already openned, and the event listener then closes the comment view.  (In turn, the comment view opens and closes immediately on each click). Thus, I changed the event listener so that the logic for the "close" event listener triggers before the open logic(and thus the close logic won't run since the comment view is still marked as closed).  
**Notes/Disclaimer:**
The same issue is also solved by …
=> Dev 105: Comment Icon opens properly on click

lib/components/dashboard/course-list/YearComponent.tsx
**Description**
When clicking on the three dots on the year component, a popup with options to remove and rename year or select terms should open. 
**Implementation**
In YearComponent.tsx, I added true to two event listeners in the useEffect that is handling the handleClickOutside. 
**Testing**
Tested locally.
=> DEV-124 fix three dots for every year to now open the popup menus

lib/components/popups/course-search/query-components/Form.tsx
When users are trying to add courses for Fall 2023, the version year does not include 2023 and the default term is not set to Fall 2023.
In Form.tsx line 91, change ``date.getMonth() < 3`` to ``date.getMonth() < 2``. The purpose of this change is to ensure that the year value for Fall 2023 is not mistakenly reduced to 2022 in cases where the code executes in March 2023. This can happen because the expression "date.getMonth()" will return 2 for March, and Fall 2023 courses were rolled out during that month.
I tested locally and ensured that the default year value and term were correct.
=> DEV-171: Correct default version year and term for Fall 2023

lib/components/popups/course-search/Cart.tsx
There was no loading icon displayed when users first open the fine requirement list in the tracker or switch between different fine requirements.
The problem occurred when users switched to a new fine requirement because the `RetrievedCourses` was not being emptied. As a result, the condition `courses.length > 0` in line 139 of CartCourseList.tsx always evaluated to true and prevented `getLoadingUI()` from being rendered. To fix the problem, I added `dispatch(updateRetrievedCourses([]));` in Cart.tsx line 67. 
Another issue was that `cartSearch()` was being executed before `cartFilter` had been fully loaded, causing all JHU courses to be loaded initially when users opened the fine requirement list. To resolve this issue, I introduced a state variable `isCartFilterLoaded`, and modified the …
=> DEV-158: Add loading logo to cart search in tracker

lib/components/dashboard/course-list/CourseList.tsx
Drag and drop duplicate course should not be allowed.
- In the backend, I have implemented a new check to identify any duplicate courses that may arise after drag and drop. If any duplicates are found, corresponding errors will be thrown. 
- In the frontend, I have updated the toast message to reflect the errors that are being thrown.
I tested locally and ensured everything works as expected.
=> DEV-157: Prevent users from duplicating courses through drag and drop

lib/components/dashboard/course-list/Semester.tsx
**Description:** 
Clicking on a comment for a semester no longer makes the year scrollable.
**Implementation:**
The comment that popups when clicking on a semester(which is within the year component) used to have the "relative" tag, but it no longer does so that the comment popup shows up a layer "above" of the year component instead of needing to scroll on the year to see the full comment.
**Testing:**
I tested locally by opening comments and making sure the comment shows up over the year.
What used to happen:
What happens now:
=> DEV-104: opening comments no longer makes year scrollable

lib/components/popups/course-search/cart/FineRequirementItem.tsx
Description: Some distributions might consist of more than one fine requirement. Each of the fine requirements are displayed in the Cart feature of the application. This Pull Request fixes a problem with the background of the fine requirement not turning green after it has been satisfied. This is an important bug to fix because it improves readbaility and user-friendliness as the user knows exactly which requirements they still need to fulfill.
Implementation: The problem here seemed to be that we originally had an isSelected prop for each fineRequirementItem which was marked as selected when clicked on. Otherwise, its background was set to white. This css property overwrote the color change which should have been produced after the requirement was completed. Simply moving everything into …
=> Fix Issue with fine requirements not turning green after being fulfilled

pages/login/[[...token]].tsx
based on the data in amplitude, even after amplitude tracking was merged into production, it seems we are still only tracking dev users. also, since dev user accounts are "staff" and "freshman", this makes the data confusing to interpret.  
in [[...token]].tsx i moved the amplitude tracking from handleJHULogin to handleDevLogin (dev user login) and handleDBLogin (jhu user login). 
in amplitude, i added another event "dev user login" in addition to "guest user login" and "jhu user login" to hopefully make things more clear. 
i also opted "TEST_DEV" and "REVIEWER_DEV" out of tracking because currently their volume of data in amplitude is super high. 
i'm hoping this can get merged into production as soon as possible! and if everything goes well in amplitude i will finally migrate from test …
=> IN-70 data analytics fixes

lib/components/popups/course-search/query-components/Form.tsx
API call should be made when search filters are changed in advanced course search.
Remove the `if (searchTerm.length > 0)` check in `lib/components/popups/course-search/query-components/Form.tsx`
I tested locally and ensured everything works as expected.
=> DEV-193: Make API call when search filters are changed

lib/components/popups/course-search/query-components/Form.tsx, lib/components/reviewer/Search.tsx, lib/resources/commonTypes.tsx
**Description:** 
On Reviewee Dashboard, we want reviewees to be able to filter their reviewee's plans by recently updated plans.
**Implementation:** 
In corresponding backend PR, mongoDB starts tracking timestamps whenever a plan is updated. Since mongoDB doesn't have timestamps for old plans(it starts tracking them whenever a course is added/removed from an old plan), those plans are "last" in the sorted order(their timestamps are just an empty string). In order to sort by most recently updated plan, we find the last updated time among all plans for each reviewee, and sort reviewees based on that time.
**Testing:** 
Tested locally by updating plans and making sure reviewer dashboard updates appropriately.
=> Dev 184: Implement Filter by Recently Updated 

lib/components/popups/course-search/query-components/Form.tsx
**Description:** Need to resolve comment saying filtering course search results by upper and lowel level is still TODO.
**Implementation:** FIltering by course search results by upper and lower level already seems to be implemented, so I deleted the TODO comment.
**Testing:**Tested locally and on ucredit.me to make sure filtering by upper and lower level courses works.
=> DEV-183: Filter results of search form by Upper/Lower level 

lib/components/dashboard/Comments.tsx, lib/services/user.service.ts
currently, deleting the last comment in a comment thread does not delete that corresponding comment thread
created removeThread in user.service.ts; in comments.tsx, when deleting comment, check if thread is empty and if so, call removeThread
tested locally
=> DEV-188 deleting last comment in thread doesn't delete that thread

lib/components/dashboard/Actionbar.tsx, lib/components/popups/DeleteCoursePopup.tsx, lib/components/popups/course-search/search-results/CourseDisplay.tsx
**Description**
A continuation of unresolved PR for DEV-46. The previous way to fix the issue triggers a new problem when adding/deleting majors and changing between plans. Now when the deleted major is the selected major for degree progress, the major in degree progress would not timely update the selected major. Similar situation occurs when changing between plan: the selected major for degree progress remains the same for different plans, even though the new plan doesn't contain the selected major for old plan.
**Implementation**
In CourseDisplay.tsx, DeleteCoursePopup.tsx, and Actionbar.tsx, add a segment of code to dispatch(updateSelectedMajor) after the dispatch(updateSelectedPlan). That is to override the "default-to-first-major" behavior set in updateSelectedPlan. 
**Testing** …
=> DEV-56 fix default major issue when changing between plans, adding/deleting majors, or adding/deleting the courses

lib/resources/majors.tsx
Description: Bug reported by JJ where EN.601.104 was not being included in the criteria for the Computer Ethics fine requirement. This bug has now been resolved.
Implementation: Added EN.601.104 to the criteria string of the Computer Ethics fine requirement in majors.tsx.
Testing: Tested by adding the Computer Ethics course and it now satisfies the requirement.
=> DEV-CE: Add EN.601.104 as criteria for computer ethics fine requirement.

lib/components/dashboard/degree-info/DistributionBarsJSX.tsx
when placeholder course number is placeholder, course updates distributions as expected. When placeholder course number is anything else like `EN.123.123`, distribution does not update after adding the placeholder. 
remove faulty boolean check; let number be anything, not necessarily 'placeholder' 
Check with course.isPlaceholder
=> DEV-79: let placeholder course name be any string

lib/components/dashboard/degree-info/CourseBar.tsx
As a user, I want to make note of distribution requirements that my plan has not yet fulfilled so that I can plan accordingly. A user wishes errors in the Tracker are more obvious. A possible solution is making the error icon red and making the check icon green.
before :
after :
=> DEV-197 Red Error Icon & Green Check Icon in Tracker

lib/components/popups/course-search/query-components/SearchList.tsx, lib/components/popups/course-search/search-results/Placeholder.tsx
- default values for placeholder area, credits, tags, & level to save a couple clicks for users
before: 
after: 
- remove 'none' option for level (now the only options are lower and upper level) because we have an error message if the user selects 'none' for level anyways
before: 
- made 'none' option lowercase for areas to keep consistent with other placeholder fields
=> DEV-198 default values for placeholder courses

lib/components/popups/CourseDisplayPopup.tsx, lib/components/popups/course-search/search-results/SisCourse.tsx
Addresses the user story (asked Sean about this and he added the below to the jira ticket):
As a user, after I look through a course’s description, I want to change the term of a course I’m taking (within the course view) and have it reflect in the dashboard, so that I don’t have to drag and drop when I have the ability to change the term in the course-specific view.
i.e. Term dropdown functionality has changed, it now reflects the semester that the user is taking the course, instead of the inspection version
- edited `SisCourse.tsx` so Term dropdown options are the years/semesters in a user's plan
- added state to store the selected year/semester that the course is to be updated to
- edited `addCourse` and `handleUpdate` methods in `CourseDisplayPopup.tsx` to take selected year/semester …
=> DEV-71: changing term in course view is reflected on dashboard

lib/resources/majors.tsx
**Description**: Some of the search features for the mol-cell major do not work, namely clicking on some of the distributions did not result in the right courses showing up in the course search. 
**Implementation:** I changed the criteria under each distribution to match the course numbers of the fine requirements criteria instead of having department tags like "AS Chemistry" or "AS Physics".
**Testing:** Tested locally
Before:
After:
=> Dev 168: Fix search features for Mol-Cell major

lib/components/dashboard/Actionbar.tsx, lib/components/dashboard/menus/comments/CommentsOverview.tsx, lib/components/popups/course-search/postreqs/PostReqSection.tsx, lib/components/popups/course-search/prereqs/PrereqDisplay.tsx, lib/resources/assets.tsx, package.json
Found a bug where clicking a course's prereq (see picture) wouldn't change the display to show that course unless it was in the current course cache. If it wasn't in the cache, it would just not do anything :(
Added a method in `assets.tsx` that searches the course cache for a given course number and if it's not there, retrieves it from the backend and adds it to the existing course. (Or returns `null` if it's nowhere to be found in these locations).
Changed `updateInspected` in `PrereqDisplay.tsx` to call this method instead of exclusively looping through course cache. If the course is found, the updates follow (as they did previously). If not, a toast is used to indicate error.
i haven't written code or made a pr in like a century i hope this wasn't horrible thanks :heart:
also idk how …
=> Bug: Fix prereq display properly updating when prereq selected 
